@php
    $maxRevenue = max(1, $revenueChart->max('revenue'));
    $statusLabels = ['pending'=>'Ожидают','processing'=>'В обработке','shipped'=>'В пути','delivered'=>'Доставлены','cancelled'=>'Отменены'];
    $statusColors = ['pending'=>'var(--warning)','processing'=>'var(--accent)','shipped'=>'#8b5cf6','delivered'=>'var(--success)','cancelled'=>'var(--danger)'];
    $statusTotal = max(1, $orderStatuses->sum());
    $offset = 0; $segments = [];
    foreach($statusLabels as $key=>$label){$value=(int)($orderStatuses[$key]??0);$end=$offset+($value/$statusTotal*100);$segments[]=$statusColors[$key].' '.$offset.'% '.$end.'%';$offset=$end;}
@endphp
<x-dashboard-layout title="Обзор платформы" active="dashboard">
<style>
.dash-head{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:24px}.stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:18px}.chart-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:18px;margin-bottom:18px}.bottom-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:18px}.metric-value{font-size:25px;font-weight:900;letter-spacing:-.03em;margin-top:12px}.metric-note{font-size:11px;color:var(--text-faint);font-weight:700;margin-top:4px}.chart-bars{height:238px;display:flex;align-items:stretch;gap:9px;padding-top:16px;border-bottom:1px solid var(--border);background:repeating-linear-gradient(to bottom,var(--border) 0 1px,transparent 1px 56px)}.chart-column{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;min-width:20px;position:relative}.chart-bar{width:min(30px,65%);min-height:4px;border-radius:7px 7px 2px 2px;background:linear-gradient(180deg,color-mix(in oklch,var(--accent) 80%,white),var(--accent));box-shadow:0 8px 20px var(--accent-soft);transition:height .6s cubic-bezier(.2,.8,.2,1),filter .2s}.chart-column:hover .chart-bar{filter:brightness(1.2)}.chart-tip{opacity:0;position:absolute;bottom:calc(var(--bar-height) + 28px);background:var(--text);color:var(--bg);font-size:10px;font-weight:900;padding:5px 7px;border-radius:6px;white-space:nowrap;pointer-events:none;transition:.15s}.chart-column:hover .chart-tip{opacity:1;transform:translateY(-3px)}.chart-label{height:26px;padding-top:8px;font-size:10px;color:var(--text-faint);text-transform:capitalize}.donut{width:154px;height:154px;border-radius:50%;background:conic-gradient({{ implode(',', $segments) }});position:relative;display:grid;place-items:center;flex-shrink:0}.donut:after{content:'';position:absolute;width:96px;height:96px;border-radius:50%;background:var(--surface)}.donut-center{z-index:1;text-align:center}.queue-row{display:flex;align-items:center;gap:11px;padding:11px 0;border-bottom:1px solid var(--border)}.queue-row:last-child{border-bottom:0}.rank{width:24px;height:24px;border-radius:7px;background:var(--surface-hover);display:grid;place-items:center;font-size:10px;font-weight:900;color:var(--text-faint)}
@media(max-width:1200px){.stats-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:820px){.chart-grid,.bottom-grid{grid-template-columns:1fr}.dash-head{align-items:flex-start;flex-direction:column}}@media(max-width:560px){.stats-grid{grid-template-columns:1fr}.chart-bars{gap:4px}.chart-label{font-size:8px}.donut{width:130px;height:130px}}
</style>
<div class="dash-head"><div><div class="page-title">Добро пожаловать, {{ Str::before(auth()->user()->name, ' ') }}</div><div class="page-subtitle">Главные показатели маркетплейса на {{ now()->locale('ru')->translatedFormat('d F Y') }}</div></div><div class="toolbar"><a href="{{ route('admin.products.create') }}" class="btn-accent"><x-icon name="plus" :size="16"/>Добавить товар</a></div></div>
<div class="stats-grid">
@foreach([
 ['Оборот платформы',number_format($stats['revenue'],0,'',' ').' TMT','cash','accent','За месяц: '.number_format($stats['thisMonthRevenue'],0,'',' ').' TMT'],
 ['Все заказы',$stats['orders'],'cart','success','Сегодня: '.$stats['todayOrders']],
 ['Средний чек',number_format($stats['averageOrder'],0,'',' ').' TMT','trending-up','warning','Динамика месяца: '.($stats['revenueGrowth']>=0?'+':'').$stats['revenueGrowth'].'%'],
 ['Активные продавцы',$stats['sellers'],'store','danger',$stats['pendingSellers'].' заявок ожидают']
] as $metric)
<div class="stat"><div style="display:flex;justify-content:space-between;align-items:start"><div><div class="kicker">{{ $metric[0] }}</div><div class="metric-value">{{ $metric[1] }}</div></div><div class="stat-icon" style="background:var(--{{ $metric[3] }}-soft);color:var(--{{ $metric[3] }})"><x-icon :name="$metric[2]" :size="18"/></div></div><div class="metric-note">{{ $metric[4] }}</div></div>
@endforeach
</div>
<div class="chart-grid">
<section class="card" style="padding:22px"><div style="display:flex;justify-content:space-between;align-items:start"><div><div style="font-size:16px;font-weight:900">Динамика продаж</div><div class="page-subtitle">Оборот за последние 12 месяцев</div></div><span class="badge" style="background:var(--accent-soft);color:var(--accent)"><x-icon name="trending-up" :size="12"/> {{ $stats['revenueGrowth']>=0?'+':'' }}{{ $stats['revenueGrowth'] }}%</span></div><div class="chart-bars">@foreach($revenueChart as $point)<div class="chart-column" style="--bar-height:{{ max(4,round($point['revenue']/$maxRevenue*190)) }}px"><div class="chart-tip">{{ number_format($point['revenue'],0,'',' ') }} TMT · {{ $point['orders'] }} зак.</div><div class="chart-bar" style="height:var(--bar-height)"></div><div class="chart-label">{{ $point['label'] }}</div></div>@endforeach</div></section>
<section class="card" style="padding:22px"><div style="font-size:16px;font-weight:900">Статусы заказов</div><div class="page-subtitle">Распределение всех заказов</div><div style="display:flex;align-items:center;justify-content:center;gap:24px;margin-top:28px;flex-wrap:wrap"><div class="donut"><div class="donut-center"><div style="font-size:24px;font-weight:900">{{ $orderStatuses->sum() }}</div><div style="font-size:10px;color:var(--text-faint)">заказов</div></div></div><div style="display:grid;gap:9px">@foreach($statusLabels as $key=>$label)<div style="display:flex;align-items:center;gap:8px;font-size:11px"><span style="width:8px;height:8px;border-radius:3px;background:{{ $statusColors[$key] }}"></span><span style="color:var(--text-muted);min-width:86px">{{ $label }}</span><strong>{{ $orderStatuses[$key]??0 }}</strong></div>@endforeach</div></div></section>
</div>
<div class="bottom-grid">
<div style="display:grid;gap:18px">
<section class="card" style="padding:22px"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px"><div><div style="font-size:16px;font-weight:900">Последние заказы</div><div class="page-subtitle">Новые операции на платформе</div></div><a href="{{ route('admin.orders') }}" style="font-size:12px;font-weight:900">Смотреть все →</a></div><div class="admin-table-wrap"><table class="admin-table" style="min-width:570px"><tbody>@forelse($recentOrders as $order)<tr><td><div style="font-weight:900">{{ $order->number }}</div><div style="font-size:10px;color:var(--text-faint)">{{ $order->created_at->diffForHumans() }}</div></td><td>{{ $order->customerName() }}</td><td><span class="badge" style="background:var(--accent-soft);color:var(--accent)">{{ $statusLabels[$order->status]??$order->status }}</span></td><td style="text-align:right;font-weight:900">{{ number_format($order->total,0,'',' ') }} TMT</td></tr>@empty<tr><td colspan="4" class="empty-state">Заказов пока нет</td></tr>@endforelse</tbody></table></div></section>
<section class="card" style="padding:22px"><div style="font-size:16px;font-weight:900;margin-bottom:5px">Топ товаров</div><div class="page-subtitle">Лидеры по количеству продаж</div>@forelse($topProducts as $product)<div class="queue-row"><div class="rank">{{ $loop->iteration }}</div><div style="flex:1;min-width:0"><div style="font-size:12px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">{{ $product->name }}</div><div style="font-size:10px;color:var(--text-faint)">{{ $product->category->name??'Без категории' }}</div></div><strong style="font-size:12px">{{ $product->sales_count }} продаж</strong></div>@empty<div class="empty-state">Нет данных о продажах</div>@endforelse</section>
</div>
<div style="display:grid;gap:18px;align-content:start">
<section class="card" style="padding:22px"><div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:16px;font-weight:900">Требует внимания</div><div class="page-subtitle">Очередь модерации</div></div><span class="badge" style="background:var(--warning-soft);color:var(--warning)">{{ $stats['pendingProducts']+$stats['pendingSellers'] }}</span></div><a href="{{ route('admin.products',['status'=>'pending']) }}" class="queue-row"><div class="stat-icon" style="background:var(--warning-soft);color:var(--warning)"><x-icon name="package" :size="17"/></div><div style="flex:1"><div style="font-size:12px;font-weight:900;color:var(--text)">Товары</div><div style="font-size:10px;color:var(--text-faint)">Проверить публикации</div></div><strong>{{ $stats['pendingProducts'] }}</strong><x-icon name="chevron-right" :size="15"/></a><a href="{{ route('admin.sellers') }}" class="queue-row"><div class="stat-icon" style="background:var(--accent-soft);color:var(--accent)"><x-icon name="store" :size="17"/></div><div style="flex:1"><div style="font-size:12px;font-weight:900;color:var(--text)">Продавцы</div><div style="font-size:10px;color:var(--text-faint)">Новые заявки</div></div><strong>{{ $stats['pendingSellers'] }}</strong><x-icon name="chevron-right" :size="15"/></a></section>
<section class="card" style="padding:22px"><div style="font-size:16px;font-weight:900">Продажи по категориям</div><div class="page-subtitle" style="margin-bottom:16px">Доля в общем обороте товаров</div>@forelse($categoryShare as $category)<div style="margin-bottom:14px"><div style="display:flex;justify-content:space-between;font-size:11px;margin-bottom:6px"><strong>{{ $category->category->name??'Без категории' }}</strong><span style="color:var(--text-faint)">{{ round($category->revenue/$totalCategoryRevenue*100) }}%</span></div><div style="height:7px;background:var(--surface-hover);border-radius:9px;overflow:hidden"><div style="height:100%;width:{{ $category->revenue/$totalCategoryRevenue*100 }}%;background:linear-gradient(90deg,var(--accent),#8b5cf6);border-radius:9px"></div></div></div>@empty<div class="empty-state">Недостаточно данных</div>@endforelse</section>
</div></div>
</x-dashboard-layout>
