<x-dashboard-layout :title="$product ? 'Редактирование товара' : 'Новый товар'" active="products">
<style>.product-editor{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:20px;align-items:start}.editor-section{padding:24px}.section-title{font-size:14px;font-weight:700;margin-bottom:18px}.upload-zone{min-height:190px;border:1.5px dashed var(--border-strong);border-radius:14px;display:flex;align-items:center;justify-content:center;text-align:center;color:var(--text-faint);cursor:pointer;overflow:hidden;position:relative;transition:.2s}.upload-zone:hover{border-color:var(--accent);background:var(--accent-soft)}.upload-zone input{position:absolute;inset:0;opacity:0;cursor:pointer}.preview-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.preview-grid img{width:100%;aspect-ratio:1;object-fit:cover;border-radius:10px;border:1px solid var(--border)}@media(max-width:900px){.product-editor{grid-template-columns:1fr}}
</style>
<div class="page-head"><div><a href="{{ route('admin.products') }}" class="back-link">← Все товары</a><div class="page-title">{{ $product ? 'Редактирование товара' : 'Новый товар' }}</div><div class="page-subtitle">Заполните информацию, цены, остаток и добавьте качественные фотографии</div></div><span class="badge" style="background:var(--success-soft);color:var(--success)">Публикация сразу</span></div>
<form method="POST" enctype="multipart/form-data" action="{{ $product ? route('admin.products.update',$product) : route('admin.products.store') }}">@csrf @if($product)@method('PUT')@endif
<div class="product-editor"><div style="display:grid;gap:20px"><section class="card editor-section"><div class="section-title">Основная информация</div><div class="form-grid"><div class="field full"><label>Название товара</label><input required class="input" name="name" value="{{ old('name',$product->name??'') }}" placeholder="Понятное название товара"></div><div class="field"><label>Категория</label><select required class="input" name="category_id"><option value="">Выберите категорию</option>@foreach($categories as $cat)<option value="{{ $cat->id }}" @selected(old('category_id',$product->category_id??'')==$cat->id)>{{ $cat->name }}</option>@endforeach</select></div><div class="field"><label>Бренд</label><input class="input" name="brand" value="{{ old('brand',$product->brand??'') }}" placeholder="Необязательно"></div><div class="field full"><label>Описание</label><textarea class="input" name="description" style="height:130px;padding:13px;resize:vertical" placeholder="Характеристики и преимущества товара">{{ old('description',$product->description??'') }}</textarea></div></div></section>
<section class="card editor-section"><div class="section-title">Цена и склад</div><div class="form-grid"><div class="field"><label>Цена, TMT</label><input required class="input" type="number" min="0" name="price" value="{{ old('price',$product->price??'') }}"></div><div class="field"><label>Цена до скидки, TMT</label><input class="input" type="number" min="0" name="compare_price" value="{{ old('compare_price',$product->compare_price??'') }}"></div><div class="field"><label>Остаток</label><input required class="input" type="number" min="0" name="stock" value="{{ old('stock',$product->stock??0) }}"></div></div></section></div>
<aside style="display:grid;gap:20px"><section class="card editor-section"><div class="section-title">Фотографии</div><label class="upload-zone" id="upload-zone"><input type="file" name="images[]" id="product-images" accept="image/*" multiple><span id="upload-copy"><x-icon name="upload" :size="28"/><br><span style="display:inline-block;margin-top:9px;font-size:12px">Выберите до 5 изображений<br><small>PNG, JPG или WEBP</small></span></span></label><div class="preview-grid" id="image-preview">@foreach($product?->images??[] as $image)<img src="{{ $image->url }}" alt="">@endforeach</div><div style="font-size:10px;color:var(--text-faint);margin-top:10px">При загрузке новых файлов текущая галерея будет заменена.</div></section>
<section class="card editor-section"><div class="section-title">Публикация</div><div style="font-size:12px;line-height:1.6;color:var(--text-muted)">Товар администратора появится в каталоге сразу после сохранения. Проверьте цену, остаток и изображения.</div><div style="display:grid;gap:9px;margin-top:20px"><button class="btn-accent">{{ $product?'Сохранить изменения':'Опубликовать товар' }}</button><a class="btn-ghost" href="{{ route('admin.products') }}">Отмена</a></div></section></aside></div>
@if($errors->any())<div class="alert alert-danger" style="margin-top:18px">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif</form>
<script>document.getElementById('product-images').addEventListener('change',function(){const box=document.getElementById('image-preview');box.innerHTML='';[...this.files].slice(0,5).forEach(file=>{const img=document.createElement('img');img.src=URL.createObjectURL(file);box.appendChild(img)})})</script>
</x-dashboard-layout>
