<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\Payment;use App\Models\SellerPayout;use App\Models\SellerTransaction;use App\Models\User;use App\Services\MarketplaceFinanceService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class FinanceController extends Controller{
 public function index(){ $transactions=SellerTransaction::with(['seller','orderItem.order'])->latest()->paginate(20);$stats=['gross'=>SellerTransaction::where('type','sale')->sum('gross_amount'),'commission'=>SellerTransaction::sum('commission_amount'),'sellerNet'=>SellerTransaction::sum('net_amount'),'pendingPayouts'=>SellerPayout::where('status','pending')->sum('amount')];return view('admin.finance.index',compact('transactions','stats'));}
 public function payments(){return view('admin.finance.payments',['payments'=>Payment::with('order.user')->latest()->paginate(20)]);}
 public function payouts(){return view('admin.finance.payouts',['payouts'=>SellerPayout::with(['seller','processor'])->latest()->paginate(20),'sellers'=>User::approvedSellers()->orderBy('store_name')->get()]);}
 public function storePayout(Request $r,MarketplaceFinanceService $finance){$d=$r->validate(['seller_id'=>['required','exists:users,id'],'amount'=>['required','integer','min:1'],'method'=>['required','in:bank_transfer,cash,card'],'note'=>['nullable','string','max:1000']]);abort_if($d['amount']>$finance->balance((int)$d['seller_id']),422,'Сумма превышает доступный баланс.');SellerPayout::create($d+['number'=>'PAY-'.strtoupper(Str::random(8))]);return back()->with('status','Выплата создана.');}
 public function completePayout(Request $r,SellerPayout $payout,MarketplaceFinanceService $finance){abort_unless($payout->status==='pending',422);DB::transaction(function()use($r,$payout,$finance){abort_if($payout->amount>$finance->balance($payout->seller_id),422,'Недостаточно средств.');SellerTransaction::create(['seller_id'=>$payout->seller_id,'type'=>'payout','net_amount'=>-$payout->amount,'status'=>'available','description'=>'Выплата '.$payout->number]);$payout->update(['status'=>'paid','processed_by'=>$r->user()->id,'processed_at'=>now(),'reference'=>$r->input('reference')]);});return back()->with('status','Выплата отмечена оплаченной.');}
}
