<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\Product;use App\Models\ProductVariant;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;
class InventoryController extends Controller{
 public function index(Request $r){$products=Product::with(['seller','variants'])->when($r->filled('q'),fn($q)=>$q->where(fn($x)=>$x->where('name','like','%'.$r->string('q').'%')->orWhere('sku','like','%'.$r->string('q').'%')->orWhere('barcode','like','%'.$r->string('q').'%')))->when($r->boolean('low'),fn($q)=>$q->whereColumn('stock','<=','low_stock_threshold'))->latest()->paginate(20)->withQueryString();return view('admin.inventory.index',compact('products'));}
 public function show(Product $product){$product->load(['variants','stockMovements.user']);return view('admin.inventory.show',compact('product'));}
 public function variant(Request $r,Product $product){$d=$r->validate(['name'=>['required','string','max:160'],'sku'=>['required','string','max:120','unique:product_variants,sku'],'barcode'=>['nullable','string','max:120','unique:product_variants,barcode'],'price'=>['nullable','integer','min:0'],'stock'=>['required','integer','min:0'],'options_text'=>['nullable','string','max:1000']]);$options=collect(explode(',',$d['options_text']??''))->mapWithKeys(function($v){$p=explode(':',$v,2);return count($p)===2?[trim($p[0])=>trim($p[1])]:[];})->all();unset($d['options_text']);$product->variants()->create($d+['options'=>$options]);return back()->with('status','Вариант создан.');}
 public function destroyVariant(Product $product,ProductVariant $variant){abort_unless($variant->product_id===$product->id,404);$variant->delete();return back()->with('status','Вариант удалён.');}
 public function adjust(Request $r,Product $product){$d=$r->validate(['quantity'=>['required','integer','not_in:0'],'reason'=>['required','string','max:1000']]);DB::transaction(function()use($r,$product,$d){$locked=Product::whereKey($product->id)->lockForUpdate()->firstOrFail();$next=$locked->stock+$d['quantity'];abort_if($next<0,422,'Остаток не может быть отрицательным.');$locked->update(['stock'=>$next]);$locked->stockMovements()->create(['user_id'=>$r->user()->id,'type'=>'adjustment','quantity'=>$d['quantity'],'balance_after'=>$next,'reason'=>$d['reason']]);});return back()->with('status','Остаток обновлён.');}
 public function export(){return response()->streamDownload(function(){$out=fopen('php://output','w');fputcsv($out,['ID','SKU','Barcode','Name','Seller','Price','Stock','Low stock']);Product::with('seller')->orderBy('id')->chunk(500,function($ps)use($out){foreach($ps as $p)fputcsv($out,[$p->id,$p->sku,$p->barcode,$p->name,$p->seller?->store_name,$p->price,$p->stock,$p->low_stock_threshold]);});fclose($out);},'inventory-'.now()->format('Y-m-d').'.csv',['Content-Type'=>'text/csv; charset=UTF-8']);}
}
