@php
$products=$items->pluck('product');$bestRating=$products->where('rating_count','>',0)->sortByDesc('rating_avg')->first();$bestPrice=$products->where('stock','>',0)->sortBy('price')->first();
$rows=[
 ['Цена',fn($p)=>number_format($p->price,0,'',' ').' TMT','price'],
 ['Скидка',fn($p)=>$p->discount_percent?'-'.$p->discount_percent.'%':'—','discount'],
 ['Рейтинг',fn($p)=>$p->rating_count?number_format($p->rating_avg,1).' / 5':'Нет оценок','rating'],
 ['Количество отзывов',fn($p)=>(string)$p->rating_count,'reviews'],
 ['Категория',fn($p)=>$p->category?->name?:'—','category'],
 ['Наличие',fn($p)=>$p->in_stock?'В наличии':'Нет в наличии','available'],
 ['Остаток',fn($p)=>$p->stock.' шт.','stock'],
 ['Продано',fn($p)=>$p->sales_count.' шт.','sales'],
 ['Продавец',fn($p)=>$p->seller?->store_name?:'AK KAGYZ','seller'],
];
@endphp
<x-layout title="Сравнение товаров">
<style>.compare-head{display:flex;align-items:flex-end;justify-content:space-between;gap:16px;margin-bottom:24px;flex-wrap:wrap}.compare-shell{border:1px solid var(--border);border-radius:20px;overflow:auto;background:var(--surface)}.compare-table{border-collapse:collapse;width:100%;min-width:760px;table-layout:fixed}.compare-table th,.compare-table td{border-right:1px solid var(--border);border-bottom:1px solid var(--border);padding:15px 18px;text-align:left;vertical-align:middle}.compare-table th:last-child,.compare-table td:last-child{border-right:0}.compare-label{width:180px;background:var(--bg-elevated);color:var(--text-faint);font-size:11px;font-weight:600;position:sticky;left:0;z-index:3}.compare-product{vertical-align:top!important;min-width:220px;padding:18px!important}.compare-image{position:relative;width:100%;aspect-ratio:1.35;background:var(--bg);border-radius:13px;display:grid;place-items:center;overflow:hidden;margin-bottom:13px}.compare-image img{width:100%;height:100%;object-fit:contain}.compare-remove{position:absolute;right:7px;top:7px;width:28px;height:28px;border-radius:9px;border:1px solid var(--border);background:color-mix(in oklch,var(--surface) 85%,transparent);color:var(--text-faint);display:grid;place-items:center}.compare-name{font-size:13px;font-weight:600;color:var(--text);line-height:1.4;display:block;min-height:38px}.compare-price{font-size:19px;font-weight:700;margin-top:7px}.best-value{color:var(--success);background:var(--success-soft)}.diff-toggle{display:flex;align-items:center;gap:8px;font-size:12px;color:var(--text-muted);cursor:pointer}.diff-toggle input{accent-color:var(--accent)}.compare-empty{max-width:500px;margin:30px auto;padding:60px 30px;text-align:center;border:1px dashed var(--border);border-radius:20px;background:var(--surface)}@media(max-width:700px){.compare-label{width:130px}.compare-table th,.compare-table td{padding:12px}.compare-product{min-width:190px}}</style>
<div class="wrap" style="padding:32px 24px 64px"><div class="compare-head"><div><div style="font-size:28px;font-weight:700;letter-spacing:-.02em;display:flex;align-items:center;gap:10px"><span style="color:var(--accent)"><x-icon name="compare" :size="24"/></span>Сравнение товаров</div><div style="font-size:13px;color:var(--text-faint);margin-top:4px">Сопоставьте характеристики и выберите подходящий вариант</div></div>@if($items->isNotEmpty())<div class="toolbar"><label class="diff-toggle"><input id="diff-only" type="checkbox">Показывать только различия</label><form method="POST" action="{{ route('compare.clear') }}" onsubmit="return confirm('Очистить список сравнения?')">@csrf @method('DELETE')<button class="btn-ghost" style="height:36px;color:var(--danger)"><x-icon name="trash" :size="14"/>Очистить</button></form></div>@endif</div>
@if($items->isEmpty())<div class="compare-empty"><div style="width:62px;height:62px;border-radius:18px;background:var(--accent-soft);color:var(--accent);display:grid;place-items:center;margin:0 auto 17px"><x-icon name="compare" :size="27"/></div><div style="font-size:19px;font-weight:700">Список сравнения пуст</div><p style="font-size:13px;color:var(--text-faint);line-height:1.6">Добавьте от двух до четырёх товаров, чтобы наглядно сравнить их характеристики.</p><a href="{{ route('catalog') }}" class="btn-accent" style="display:inline-flex">Выбрать товары</a></div>@else
<div class="compare-shell"><table class="compare-table"><thead><tr><th class="compare-label"><div style="font-size:13px;color:var(--text);font-weight:700">{{ $items->count() }} из 4</div><div style="font-size:10px;margin-top:3px">товаров добавлено</div></th>@foreach($items as $item)@php($p=$item->product)@php($image=$p->images->first())<th class="compare-product"><div class="compare-image">@if($image)<img src="{{ $image->url }}" alt="{{ $p->name }}" loading="lazy">@else<x-icon name="image" :size="30"/>@endif<form method="POST" action="{{ route('compare.toggle',$p) }}">@csrf<button class="compare-remove" title="Убрать"><x-icon name="x" :size="13"/></button></form>@if($bestRating?->id===$p->id)<span class="badge" style="position:absolute;left:7px;top:7px;background:var(--accent);color:white">Лучший рейтинг</span>@endif</div><a class="compare-name" href="{{ route($p->seller_id?'marketplace.products.show':'products.show',$p->slug) }}">{{ $p->name }}</a><div class="compare-price">{{ number_format($p->price,0,'',' ') }} TMT</div>@if($p->in_stock)<form method="POST" action="{{ route('cart.add',$p) }}">@csrf<button class="btn-accent" style="width:100%;height:36px;font-size:11px;margin-top:12px"><x-icon name="cart" :size="14"/>В корзину</button></form>@else<button disabled class="btn-ghost" style="width:100%;height:36px;margin-top:12px;opacity:.6">Нет в наличии</button>@endif</th>@endforeach</tr></thead><tbody>@foreach($rows as [$label,$value,$key])@php($values=$products->map(fn($p)=>$value($p))->unique())<tr class="compare-row" data-different="{{ $values->count()>1?'1':'0' }}"><td class="compare-label">{{ $label }}</td>@foreach($items as $item)@php($p=$item->product)<td class="{{ ($key==='price'&&$bestPrice?->id===$p->id)||($key==='rating'&&$bestRating?->id===$p->id)?'best-value':'' }}">{{ $value($p) }}</td>@endforeach</tr>@endforeach<tr data-different="1"><td class="compare-label">Описание</td>@foreach($items as $item)<td style="font-size:11px;color:var(--text-muted);line-height:1.55">{{ Str::limit($item->product->description?:'Описание не добавлено',180) }}</td>@endforeach</tr></tbody></table></div>@endif</div>
<script>document.getElementById('diff-only')?.addEventListener('change',function(){document.querySelectorAll('.compare-row').forEach(row=>row.style.display=this.checked&&row.dataset.different==='0'?'none':'table-row')})</script>
</x-layout>
